<!--
  The extension builder on /guide/builder: pick a catalog model, add attributes
  of your own, and get the @context and the JSON Schema for them. The files are
  generated by scripts/lib/extend.mjs (tested there); the model data comes from
  catalog.data.mjs at build time. ?model=<subject>/<Type> preselects a model.
-->
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { data } from './catalog.data.mjs'
import { buildExtension, proposalUrl } from '../../../scripts/lib/extend.mjs'

const props = defineProps<{ lang: 'ja' | 'en' }>()
const L = {
  ja: {
    model: 'モデル', prefix: '接頭辞', base: '名前空間（あなたの IRI）', attributes: 'あなたの属性', add: '属性を追加', remove: '削除',
    name: '属性名', ngsiType: 'NGSI-LD の型', valueType: '値の型', format: '書式', required: '必須', description: '説明', none: 'なし',
    context: 'あなたの @context', schema: 'JSON Schema（カタログの属性 + あなたの属性）', copy: 'コピー', copied: 'コピーしました',
    propose: 'この属性がカタログにあるべきなら、提案フォームで知らせてください（内容は入力済み）。',
    schemaNote: (v: string) => `カタログのスキーマは閉じている（additionalProperties: false）ため、参照だけでは属性を足せません。これは ${v} をもとに作ったもので、新しいバージョンに移るときは作り直してください。$id はあなたの URL に書き換えてください。`,
    problems: {
      prefix: '接頭辞は英小文字で始まる英小文字・数字・ハイフンにしてください（例 acme）。', prefixReserved: (n: string) => `接頭辞「${n}」は NGSI-LD で予約されています。`,
      base: '名前空間は http(s) の URL で、/ か # で終わるものにしてください（例 https://example.com/ns/acme/）。',
      baseTaken: 'datamodels.jp と uri.etsi.org の名前空間はカタログと NGSI-LD のものです。あなたのドメインを使ってください。',
      none: '属性を 1 つ以上入力してください。', name: (n: string) => `「${n}」: 属性名は英小文字で始まる英数字（camelCase）にしてください。`,
      inModel: (n: string) => `「${n}」はこのモデルに既にあります。そのまま使ってください（意味を変えてはいけません）。`,
      reserved: (n: string) => `「${n}」は NGSI-LD コアの予約語です。別の名前にしてください。`,
      inContext: (n: string) => `「${n}」はこのサブジェクトの @context で別の属性として定義済みです。同じ意味ならその属性を使い、違う意味なら別の名前にしてください。`,
      prefixInContext: (n: string) => `接頭辞「${n}」はこのサブジェクトの @context で属性名として使われています。別の接頭辞にしてください。`, duplicate: (n: string) => `「${n}」が 2 回あります。`,
      valueType: (n: string) => `「${n}」: 値の型を選んでください。`, format: (n: string) => `「${n}」: 書式が不正です。`, ngsiType: (n: string) => `「${n}」: NGSI-LD の型を選んでください。`,
    } as Record<string, any>,
  },
  en: {
    model: 'Model', prefix: 'Prefix', base: 'Namespace (your IRIs)', attributes: 'Your attributes', add: 'Add an attribute', remove: 'Remove',
    name: 'Name', ngsiType: 'NGSI-LD type', valueType: 'Value type', format: 'Format', required: 'Required', description: 'Description', none: 'none',
    context: 'Your @context', schema: 'JSON Schema (the catalog attributes plus yours)', copy: 'Copy', copied: 'Copied',
    propose: 'If these attributes belong in the catalog, tell us with the proposal form (filled in for you).',
    schemaNote: (v: string) => `The catalog schemas are closed (additionalProperties: false), so a schema that only references them cannot add attributes. This one starts from ${v}; generate it again when you move to a new version, and replace $id with your own URL.`,
    problems: {
      prefix: 'The prefix starts with a lower-case letter and has only lower-case letters, digits and hyphens (for example acme).', prefixReserved: (n: string) => `The prefix "${n}" is reserved by NGSI-LD.`,
      base: 'The namespace is an http(s) URL ending in / or # (for example https://example.com/ns/acme/).',
      baseTaken: 'The datamodels.jp and uri.etsi.org namespaces belong to the catalog and to NGSI-LD. Use your own domain.',
      none: 'Enter at least one attribute.', name: (n: string) => `"${n}": a name starts with a lower-case letter and has only letters and digits (camelCase).`,
      inModel: (n: string) => `"${n}" is already in this model. Use it as it is (its meaning must not change).`,
      reserved: (n: string) => `"${n}" is a protected term of the NGSI-LD core context. Choose another name.`,
      inContext: (n: string) => `"${n}" is already defined by this subject's @context, for another model. Use that attribute if it means the same, otherwise choose another name.`,
      prefixInContext: (n: string) => `The prefix "${n}" is already a term of this subject's @context. Choose another prefix.`, duplicate: (n: string) => `"${n}" appears twice.`,
      valueType: (n: string) => `"${n}": choose a value type.`, format: (n: string) => `"${n}": unknown format.`, ngsiType: (n: string) => `"${n}": choose an NGSI-LD type.`,
    } as Record<string, any>,
  },
}[props.lang]

const coreTerms = new Set<string>(data.coreTerms)
const modelId = ref(data.models.find((m: any) => m.id === 'transportation/RoadRestriction')?.id ?? data.models[0].id)
const model = computed(() => data.models.find((m: any) => m.id === modelId.value))
const form = reactive({
  prefix: 'acme', base: 'https://example.com/ns/acme/',
  attributes: [{ name: 'patrolRoute', ngsiType: 'Property', valueType: 'string', format: '', required: false, description: '' }] as any[],
})
onMounted(() => {
  const wanted = new URLSearchParams(location.search).get('model')
  if (wanted && data.models.some((m: any) => m.id === wanted)) modelId.value = wanted
})

const result = computed(() => buildExtension(model.value, form, coreTerms))
const messages = computed(() => result.value.problems.map((p) => { const m = L.problems[p.code]; return typeof m === 'function' ? m(p.name) : m }))
const pretty = (v: unknown) => JSON.stringify(v, null, 2)
const proposal = computed(() => proposalUrl(model.value, form.attributes))
const subjects = computed(() => [...new Set(data.models.map((m: any) => m.subject))].map((s) => ({ s, title: data.models.find((m: any) => m.subject === s).subjectTitle[props.lang], models: data.models.filter((m: any) => m.subject === s) })))

const add = () => form.attributes.push({ name: '', ngsiType: 'Property', valueType: 'string', format: '', required: false, description: '' })
const copied = ref('')
async function copy(which: 'context' | 'schema') {
  const text = pretty(which === 'context' ? result.value.context : result.value.schema)
  try { await navigator.clipboard.writeText(text); copied.value = which; setTimeout(() => (copied.value = ''), 1500) } catch { /* the text stays selectable */ }
}
</script>

<template>
  <div class="extension-builder">
    <div class="fields">
      <label>{{ L.model }}
        <select v-model="modelId">
          <optgroup v-for="g in subjects" :key="g.s" :label="g.title">
            <option v-for="m in g.models" :key="m.id" :value="m.id">{{ m.type }} — {{ m.title[lang] }}</option>
          </optgroup>
        </select>
      </label>
      <label>{{ L.prefix }}<input v-model="form.prefix" spellcheck="false" autocapitalize="off" /></label>
      <label class="wide">{{ L.base }}<input v-model="form.base" spellcheck="false" autocapitalize="off" /></label>
    </div>

    <h3>{{ L.attributes }}</h3>
    <div class="attrs">
      <div v-for="(a, i) in form.attributes" :key="i" class="attr">
        <label>{{ L.name }}<input v-model="a.name" spellcheck="false" autocapitalize="off" /></label>
        <label>{{ L.ngsiType }}
          <select v-model="a.ngsiType"><option>Property</option><option>Relationship</option><option>GeoProperty</option></select>
        </label>
        <label v-if="a.ngsiType === 'Property'">{{ L.valueType }}
          <select v-model="a.valueType"><option v-for="v in ['string', 'number', 'integer', 'boolean', 'object', 'array']" :key="v">{{ v }}</option></select>
        </label>
        <label v-if="a.ngsiType === 'Property' && a.valueType === 'string'">{{ L.format }}
          <select v-model="a.format"><option value="">{{ L.none }}</option><option>date-time</option><option>date</option><option>uri</option></select>
        </label>
        <label class="check"><input v-model="a.required" type="checkbox" />{{ L.required }}</label>
        <label class="wide">{{ L.description }}<input v-model="a.description" /></label>
        <button type="button" class="remove" @click="form.attributes.splice(i, 1)">{{ L.remove }}</button>
      </div>
      <button type="button" class="add" @click="add">+ {{ L.add }}</button>
    </div>

    <div v-if="messages.length" class="problems" aria-live="polite"><ul><li v-for="(m, i) in messages" :key="i">{{ m }}</li></ul></div>
    <template v-else>
      <div class="out">
        <div class="head"><h3>{{ L.context }}</h3><button type="button" @click="copy('context')">{{ copied === 'context' ? L.copied : L.copy }}</button></div>
        <pre><code>{{ pretty(result.context) }}</code></pre>
      </div>
      <div class="out">
        <div class="head"><h3>{{ L.schema }}</h3><button type="button" @click="copy('schema')">{{ copied === 'schema' ? L.copied : L.copy }}</button></div>
        <p class="note">{{ L.schemaNote(model.schemaExact) }}</p>
        <pre class="long"><code>{{ pretty(result.schema) }}</code></pre>
      </div>
      <p><a :href="proposal" target="_blank" rel="noreferrer">{{ L.propose }}</a></p>
    </template>
  </div>
</template>

<style scoped>
.fields, .attr { display: flex; flex-wrap: wrap; gap: 8px 12px; align-items: flex-end; }
label { display: flex; flex-direction: column; gap: 2px; font-size: 13px; color: var(--vp-c-text-2); min-width: 0; }
label.wide { flex: 1 1 260px; }
label.check { flex-direction: row; align-items: center; gap: 6px; padding-bottom: 6px; }
input:not([type=checkbox]), select { padding: 4px 8px; font-size: 14px; color: var(--vp-c-text-1); background: var(--vp-c-bg); border: 1px solid var(--vp-c-divider); border-radius: 6px; min-width: 0; }
.fields input, .attr input:not([type=checkbox]) { font-family: var(--vp-font-family-mono); }
label.wide input { width: 100%; }
.attrs { display: flex; flex-direction: column; gap: 10px; }
.attr { padding: 10px; border: 1px solid var(--vp-c-divider); border-radius: 8px; }
button { padding: 4px 12px; font-size: 14px; border: 1px solid var(--vp-c-divider); border-radius: 8px; color: var(--vp-c-text-2); }
button:hover { color: var(--vp-c-brand-1); }
.add { align-self: flex-start; }
.problems { margin: 12px 0; padding: 8px 12px; border-radius: 8px; background: var(--vp-c-warning-soft); color: var(--vp-c-warning-1); font-size: 14px; }
.problems ul { margin: 0; padding-left: 20px; }
.out .head { display: flex; justify-content: space-between; align-items: center; margin-top: 20px; }
.out h3 { margin: 0; }
.note { font-size: 13px; color: var(--vp-c-text-2); }
pre { margin: 8px 0; padding: 12px; overflow: auto; font-size: 13px; line-height: 1.5; background: var(--vp-c-bg-alt); border-radius: 8px; }
pre.long { max-height: 420px; }
</style>
